import { Product, StoreSettings, Coupon, Review, Category } from '../types';

export const INITIAL_SETTINGS: StoreSettings = {
  id: 'general',
  storeName: 'TWAKX Smart Accessories & Gadgets',
  tagline: 'Premium Mobile & Electronics Accessories in Pakistan',
  whatsappNumber: '03352732395',
  phoneNumber: '03352732395',
  supportEmail: 'muhammadali7394@gmail.com',
  easypaisaNumber: '03378018331',
  easypaisaAccountName: 'Nighat Ali',
  jazzcashNumber: '03352732395',
  jazzcashAccountName: 'TWAKX Official',
  bankName: 'Meezan Bank Ltd',
  bankAccountTitle: 'TWAKX Smart Accessories',
  bankAccountNumber: '02010108924719',
  bankIBAN: 'PK72MEZN0002010108924719',
  freeShippingThreshold: 3000,
  standardShippingFee: 200,
  announcementText: '🔥 Free Express Shipping on All Orders Over ₨ 3,000 across Pakistan! | 🚚 Fast 2-3 Days Delivery',
  bannerActive: true,
  deliveryTimeEstimate: '2 to 3 Working Days (Nationwide via TCS / Trax)',
};

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coupon-1',
    code: 'TWAKX10',
    discountType: 'percentage',
    discountValue: 10,
    minOrderAmount: 2000,
    isActive: true,
    description: '10% OFF on all accessories above ₨ 2,000',
  },
  {
    id: 'coupon-2',
    code: 'FREESHIP',
    discountType: 'fixed',
    discountValue: 200,
    minOrderAmount: 1500,
    isActive: true,
    description: 'Free Shipping Voucher (₨ 200 discount)',
  },
  {
    id: 'coupon-3',
    code: 'WELCOME500',
    discountType: 'fixed',
    discountValue: 500,
    minOrderAmount: 4500,
    isActive: true,
    description: '₨ 500 Flat OFF on Smart Watches & Earbuds above ₨ 4,500',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'wireless-earbuds',
    name: 'Wireless Earbuds',
    slug: 'wireless-earbuds',
    icon: 'Headphones',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80',
    description: 'ANC, Gaming Low Latency & High Fidelity TWS Earbuds',
    isFeatured: true,
    displayOrder: 1,
  },
  {
    id: 'smart-watches',
    name: 'Smart Watches',
    slug: 'smart-watches',
    icon: 'Watch',
    image: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&auto=format&fit=crop&q=80',
    description: 'AMOLED Displays, Bluetooth Calling & Health Tracking',
    isFeatured: true,
    displayOrder: 2,
  },
  {
    id: 'headphones',
    name: 'Headphones',
    slug: 'headphones',
    icon: 'Radio',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    description: 'Over-Ear Studio Bass & Noise Cancelling Wireless Headphones',
    isFeatured: true,
    displayOrder: 3,
  },
  {
    id: 'mobile-accessories',
    name: 'Mobile Accessories',
    slug: 'mobile-accessories',
    icon: 'Smartphone',
    image: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=600&auto=format&fit=crop&q=80',
    description: 'Cases, Screen Protectors, Lens Guards & Holders',
    isFeatured: true,
    displayOrder: 4,
  },
  {
    id: 'chargers-cables',
    name: 'Chargers & Cables',
    slug: 'chargers-cables',
    icon: 'Zap',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop&q=80',
    description: 'GaN 65W/100W Fast Adapters & Braided Type-C Lightning Cables',
    isFeatured: true,
    displayOrder: 5,
  },
  {
    id: 'power-banks',
    name: 'Power Banks',
    slug: 'power-banks',
    icon: 'BatteryCharging',
    image: 'https://images.unsplash.com/photo-1609592426815-53efbbcead05?w=600&auto=format&fit=crop&q=80',
    description: '10000mAh to 30000mAh PD Fast Charge Portable Batteries',
    isFeatured: true,
    displayOrder: 6,
  },
  {
    id: 'laptop-accessories',
    name: 'Laptop Accessories',
    slug: 'laptop-accessories',
    icon: 'Laptop',
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80',
    description: 'USB-C Hubs, Cooling Pads, Ergonomic Stands & Sleeves',
    isFeatured: true,
    displayOrder: 7,
  },
  {
    id: 'gaming-accessories',
    name: 'Gaming Accessories',
    slug: 'gaming-accessories',
    icon: 'Gamepad2',
    image: 'https://images.unsplash.com/photo-1612287233215-ff5d56b06385?w=600&auto=format&fit=crop&q=80',
    description: 'RGB Headsets, Finger Sleeves & Low-Latency Gaming Triggers',
    isFeatured: true,
    displayOrder: 8,
  },
  {
    id: 'speakers',
    name: 'Speakers',
    slug: 'speakers',
    icon: 'Volume2',
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80',
    description: 'Portable Waterproof Bluetooth Speakers & Bass Cannons',
    isFeatured: true,
    displayOrder: 9,
  },
  {
    id: 'gadgets',
    name: 'Other Gadgets',
    slug: 'gadgets',
    icon: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop&q=80',
    description: 'Car Phone Mounts, Stylus Pens & Smart Home Accessories',
    isFeatured: true,
    displayOrder: 10,
  },
];

export const CATEGORIES = INITIAL_CATEGORIES;

export const INITIAL_PRODUCTS: Product[] = [];

export const INITIAL_REVIEWS: Review[] = [];

export const PAKISTAN_CITIES = [
  'Karachi',
  'Lahore',
  'Islamabad',
  'Rawalpindi',
  'Faisalabad',
  'Multan',
  'Peshawar',
  'Quetta',
  'Sialkot',
  'Gujranwala',
  'Hyderabad',
  'Abbottabad',
  'Bahawalpur',
  'Sargodha',
  'Sukkur',
  'Rahim Yar Khan',
  'Gujrat',
  'Sheikhupura',
  'Jhelum',
  'Mardan',
  'Muzaffarabad (AJK)',
  'Mirpur (AJK)',
  'Gilgit',
  'Swat',
];
